[package]
name = "delay-data-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
futures = "0.3.30"
pin-project = "1.1.5"
tokio = { version = "1.38.1", features = ["rt", "sync", "time"] }